package com.example.easycoin;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="coin")
public class Coin {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Coin(int id, String name, String symbol, double price, double change24h, boolean favourite) {
        this.name = name;
        this.symbol = symbol;
        this.price = price;
        this.change24h = change24h;
        this.favourite = favourite;
    }

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    @ColumnInfo(name = "name")
    public String name;

    @ColumnInfo(name = "symbol")
    public String symbol;

    @ColumnInfo(name = "price")
    public double price;

    @ColumnInfo(name = "change24h")
    public double change24h;

    @ColumnInfo(name = "favourite")
    public boolean favourite;

}
