package com.example.easycoin;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="coin")
public class Coin {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Coin(int id, String favouriteCoin) {
        this.id = id;
        this.favouriteCoin = favouriteCoin;
    }

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    @ColumnInfo(name = "favouriteCoin")
    public String favouriteCoin;

}
